services:

  _defaults:
    public: true
    autowire: true

  Github\Client:
    class: Github\Client
    calls:
      - [ authenticate, [ '%env(GITHUB_TOKEN)%', 'null', 'access_token_header' ] ]

  emteknetnz\JsUpdater\Services\GitHubService: ~
  emteknetnz\JsUpdater\Services\ModuleService: ~
