parameters:
  github_token: '%env(SS_HOST)%'

services:

  _defaults:
    public: true
    autowire: true

  Github\Client: ~
  emteknetnz\JsUpdater\Services\GitHubService: ~
  emteknetnz\JsUpdater\Services\ModuleService: ~
